[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dbotu_q2"
version = "2019.1"
description = "Distribution-based clustering"
authors = [
    { name = "Claire Duvallet", email = "cduvallet@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.6"
urls = { Homepage = "https://github.com/cduvallet/q2-dbotu" }

dependencies = [
    "dbotu",
    "pandas",
    "scikit-bio"
]

[project.entry-points."qiime2.plugins"]
dbotu_q2 = "dbotu_q2.plugin_setup:plugin"

[tool.setuptools.packages.find]
where = ["."]
include = ["dbotu_q2"]

[tool.setuptools.package-data]
"dbotu_q2" = ["citations.bib"]

